volumes:
  postgres:
  redpanda:
  restate:

services:
  postgres:
    image: docker.io/postgres:16.4-alpine3.19
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - 'POSTGRES_DATABASE=${DATABASE_NAME}'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.2
    ports:
      - '8081:8081'
      - '8082:8082'
      - '9092:9092'
      - '19644:9644'

  restate:
    image: docker.io/restatedev/restate:1.0
    ports:
      - '8080:8080'
      - '9070:9070'
    environment:
      - 'RESTATE_CONFIG=/etc/config/restate.toml'
    volumes:
      - ./infra/restate/config.toml:/etc/config/restate.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
